### ISSUE TITLE
Adding New: SectionGroup and ElementCollection are switched

### ISSUE THREAD

**Issue by Tachionstrahl** [hybridview/ConfigurationSectionDesigner#9] opened 2018-07-17 12:59 UTC
![sectiondesignerbug](https://user-images.githubusercontent.com/38250198/42818660-c7d9e86c-89d1-11e8-9f9b-3bdb816c23ff.gif)

**Comment by hybridview** [comment] 2018-08-03 18:26
Seems like a simple fix. I'll take a look.

**Comment by hybridview** [comment] 2018-08-03 19:50
I can reproduce this, but all the code in the project is absolutely correct. I went over it several times. 
 There is a chance that my compiled version does not match the latest version in source control, and that is the only cause I can think of. It's strange, because I see no history in the repo showing a fix for this.

**Comment by hybridview** [comment] 2019-04-11 21:30
Finally found and fixed this issue. Will be included in today's release.

**Closed as completed by hybridview** 2019-04-11 21:30 UTC
